<%@ control language="C#" autoeventwireup="true" inherits="Widgets.Newsletter.Edit, App_Web_le1y5xbp" %>
<asp:GridView 
  runat="server"
  id="gridEmails"
  AlternatingRowStyle-BackColor="#F1F1F1"
  AutoGenerateColumns="False"
  AutoGenerateDeleteButton="true">
 
  <Columns>
    <asp:BoundField HeaderText="Email" DataField="innertext" />
  </Columns> 
</asp:GridView>